export const FETCH_CRYPTOCURRENCY_LIST = 'FETCH_CRYPTOCURRENCY_LIST';
export const GET_CRYPTOCURRENCY_LIST = 'GET_CRYPTOCURRENCY_LIST';
export const LOADING_CRYPTOCURRENCY_LIST = 'LOADING_CRYPTOCURRENCY_LIST';
export const LOADING_CRYPTOCURRENCY_LIST_SUCCESS = 'LOADING_CRYPTOCURRENCY_LIST_SUCCESS';
export const LOADING_CRYPTOCURRENCY_LIST_ERROR = 'LOADING_CRYPTOCURRENCY_LIST_ERROR';

export const FETCH_CRYPTOCURRENCY_DETAILS = 'FETCH_CRYPTOCURRENCY_DETAILS';
export const GET_CRYPTOCURRENCY_DETAILS = 'GET_CRYPTOCURRENCY_DETAILS';
export const LOADING_CRYPTOCURRENCY_DETAILS = 'LOADING_CRYPTOCURRENCY_DETAILS';
export const LOADING_CRYPTOCURRENCY_DETAILS_SUCCESS = 'LOADING_CRYPTOCURRENCY_DETAILS_SUCCESS';
export const LOADING_CRYPTOCURRENCY_DETAILS_ERROR = 'LOADING_CRYPTOCURRENCY_DETAILS_ERROR';

export const SORT_DIRECTION = 'SORT_DIRECTION';
export const SORT_BY = 'SORT_BY';

export const SET_NAV_URL = 'SET_NAV_URL';
export const GET_NAV_URL = 'GET_NAV_URL';
